### ISSUE TITLE
Bug: OCE performance scan failing upon hitting 10x.gsa.gov

### ISSUE THREAD

**Issue by maomeara63** [GSA-TTS/10x-website#127]
### Who discovered this?

Jonah Hatfield

### What happened?

`10x site is throwing a weird error when we try to crawl the site for the 9 performance metrics GSA reports to OMB every quarter. The error stops the crawling script, forcing [@Jonah Hatfield - IR](mailto:jonah.hatfield@gsa.gov) to manually eliminate it from the list in order to continue. The error is: "Error: Node is either not clickable or not an HTMLElement"
`

**Comment by jonadecker** [comment]
Followed up with original reporter. The script was looking for the GSA Privacy Policy link, but 10x has an exemption to that requirement because our privacy policy needs to include information about IA submissions.

The script has been updated to point to the correct 10x url and is no longer failing.
