### ISSUE TITLE
Bug: Privacy policy broken link

### ISSUE THREAD

**Issue by maomeara63** [GSA-TTS/10x-website#209]
### Who discovered this?

Marina

### What happened?

Link to GSA privacy policy is broken

### What pages did this appear on?

Privacy policy has a broken link

### Detail the steps for someone to reproduce

https://10x.gsa.gov/privacy-policy/ > click on link at the bottom of the page

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

N/A

**Comment by maomeara63** [comment]
It appears that the link is broken because GSA has consolidated a bunch of info onto a single page of Website Policies. 

We could 

1. Link to the specific [Privacy Policy](https://www.gsa.gov/website-information/website-policies#privacy:~:text=mission%20or%20policies.-,Privacy%20and%20security,-We%20will%20collect) info. 
2. Pull the relevant content into the 10x website page. 
3. Something else I haven't thought of.

I don't recommend option 1; it seems like that page is not really public-facing.

@marina-defrates @jonadecker

**Comment by jonadecker** [comment]
I think the correct link is the Privacy section on the Website Policies page, which is the content we were linking to before, if not the page. 10x is already a departure in having their own Privacy Policy (because of idea submissions), we just have to keep up with the evolving page landscape at GSA I guess.

I can update to https://www.gsa.gov/website-information/website-policies#privacy @marina-defrates ?

**Comment by jonadecker** [comment]
closed by pr #210
